import { Card } from '@/components/ui/card';
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '@/components/ui/accordion';
import { HelpCircle } from 'lucide-react';

export const FAQ = () => {
	const faqs = [
		{
			question: "What is a CS2 crosshair share code?",
			answer: "A share code is a unique identifier generated by Counter-Strike 2 that contains all your crosshair settings. You can find it in-game by going to Settings → Crosshair → Share or Import. It always starts with 'CSGO-' followed by five groups of characters separated by hyphens."
		},
		{
			question: "How do delli.cc crosshair share links work?",
			answer: "Every valid crosshair code becomes a shareable URL automatically. Paste or load a code, then copy the Share Link button or the address bar URL. Anyone opening that delli.cc/?code=CSGO-... link lands on this tool with the same active crosshair already applied."
		},
		{
			question: "Where do I place the generated config file?",
			answer: "Place the .cfg file in your CS2 config folder, which is typically located at: C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo\\cfg. If you're on a different platform or custom Steam library location, adjust the path accordingly."
		},
		{
			question: "How do I execute the config file in-game?",
			answer: "Open the developer console in CS2 (press ~ or ` key) and type: exec crosshair.cfg (or exec crosshair_youraliasname.cfg if you used an alias). You can also add this command to your autoexec.cfg file to load it automatically when you launch the game."
		},
		{
			question: "What is an alias and why should I use one?",
			answer: "An alias is a shortcut command in CS2. By naming your crosshair config with an alias, you can quickly switch between different crosshairs in-game by simply typing the alias name in console. For example, if you name it 'sniper', you can type 'sniper' in console to instantly load that crosshair. This is useful if you want different crosshairs for different weapons or situations."
		},
		{
			question: "Can I have multiple crosshair configs?",
			answer: "Absolutely! You can generate as many config files as you want with different aliases. This allows you to switch between different crosshairs instantly during gameplay. For example, you could have 'rifle', 'awp', 'pistol', etc., and switch between them as needed."
		},
		{
			question: "Will this work with the latest CS2 update?",
			answer: "Yes! This tool uses the official CS2 crosshair encoding format, which is maintained by Valve. As long as CS2 supports share codes (which is a core feature), this tool will work. The config files use standard console variables (convars) that have been stable since CS:GO."
		},
		{
			question: "Is my data stored or sent anywhere?",
			answer: "No! All processing happens locally in your browser. Your share codes and generated configs never leave your device. We don't have any servers collecting data. The only data stored is your recent history and favorites, which are saved locally in your browser's localStorage for your convenience."
		},
		{
			question: "My crosshair looks different in-game than in the preview. Why?",
			answer: "The preview is a close approximation of how your crosshair will look in CS2. Minor differences can occur due to different screen resolutions, aspect ratios, or in-game scaling settings. The config file will apply the exact settings from your share code."
		},
		{
			question: "Can I use this with a autoexec.cfg file?",
			answer: "Yes! After generating your config file, you can add the exec command to your autoexec.cfg. For example, add 'exec crosshair.cfg' to automatically load your crosshair every time you launch CS2. You can also bind crosshair switches to keys using bind commands."
		},
		{
			question: "What's the difference between downloading and copying to clipboard?",
			answer: "Downloading creates a .cfg file that you need to place in your CS2 config folder manually. Copying to clipboard gives you the raw text that you can paste directly into an existing config file or your autoexec.cfg. Both methods work equally well - choose based on your preference."
		},
		{
			question: "How do I enable the developer console in CS2?",
			answer: "Go to Settings → Game → Game Settings and enable 'Enable Developer Console (~)'. Then you can open it by pressing the ~ or ` key (usually below Escape on your keyboard). You'll need the console to execute config files and use aliases."
		},
		{
			question: "Can I share my crosshair config with friends?",
			answer: "Yes. The built-in Share Link action copies a delli.cc/?code=CSGO-... URL that opens this tool with your crosshair already active. You can still share the raw CS2 code or generated .cfg file if that fits your workflow better."
		}
	];

	return (
		<Card className="p-6 md:p-8 bg-card/30 border-tactical-blue/20 animate-[slide-in-up_0.5s_ease-out_0.4s_both]">
			<div className="flex items-center gap-3 mb-6">
				<HelpCircle className="w-6 h-6 text-neon-cyan" />
				<h3 className="text-2xl font-semibold text-neon-cyan">Frequently Asked Questions</h3>
			</div>

			<Accordion type="single" collapsible className="w-full">
				{faqs.map((faq, index) => (
					<AccordionItem key={index} value={`item-${index}`}>
						<AccordionTrigger className="text-left hover:text-neon-cyan transition-colors">
							{faq.question}
						</AccordionTrigger>
						<AccordionContent className="text-muted-foreground leading-relaxed">
							{faq.answer}
						</AccordionContent>
					</AccordionItem>
				))}
			</Accordion>

			<div className="mt-6 pt-6 border-t border-tactical-blue/20">
				<p className="text-sm text-muted-foreground text-center">
					Still have questions? This tool is open-source and community-driven. Feel free to reach out or contribute!
				</p>
			</div>
		</Card>
	);
};
