import { Card } from '@/components/ui/card';
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '@/components/ui/accordion';
import { HelpCircle } from 'lucide-react';

export const FAQ = () => {
	const faqs = [
		{
			question: "What is a CS2 crosshair share code?",
			answer: "A share code is a unique identifier generated by Counter-Strike 2 that contains all your crosshair settings. You can find it in-game by going to Settings → Crosshair → Share or Import. It always starts with 'CSGO-' followed by five groups of characters separated by hyphens."
		},
		{
			question: "How do I apply the generated crosshair?",
			answer: "The fastest option is Copy Command: open the CS2 developer console, paste, and press Enter. For a reusable file, download the .cfg into your CS2 game/csgo/cfg folder and run exec filename.cfg."
		},
		{
			question: "How do share links and aliases work?",
			answer: "Copy Share Link creates a delli.cc URL that reloads the same crosshair. An optional alias creates a short console name for a downloaded config, making it easy to switch between several saved crosshairs."
		},
		{
			question: "Is my data stored or sent anywhere?",
			answer: "No! All processing happens locally in your browser. Your share codes and generated configs never leave your device. We don't have any servers collecting data. The only data stored is your recent history and favorites, which are saved locally in your browser's localStorage for your convenience."
		},
		{
			question: "My crosshair looks different in-game than in the preview. Why?",
			answer: "The preview is a close approximation of how your crosshair will look in CS2. Minor differences can occur due to different screen resolutions, aspect ratios, or in-game scaling settings. The config file will apply the exact settings from your share code."
		},
	];

	return (
		<Card id="help" className="border-tactical-blue/20 bg-card/30 p-5 md:p-6">
			<div className="mb-3 flex items-center gap-2">
				<HelpCircle className="h-5 w-5 text-neon-cyan" />
				<h2 className="text-lg font-semibold text-neon-cyan">Quick help</h2>
			</div>

			<Accordion type="single" collapsible className="w-full">
				{faqs.map((faq, index) => (
					<AccordionItem key={index} value={`item-${index}`}>
						<AccordionTrigger className="py-3 text-left text-sm transition-colors hover:text-neon-cyan">
							{faq.question}
						</AccordionTrigger>
						<AccordionContent className="text-muted-foreground leading-relaxed">
							{faq.answer}
						</AccordionContent>
					</AccordionItem>
				))}
			</Accordion>
		</Card>
	);
};
